GET http://localhost:8080/api/users/me 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM2MTUwMjAwLCJleHAiOjE3Mzg3NDIyMDB9._g8KHG54OVNmIlpPhi6Zct5LwNMB7zQmdugi76OyhtY
